# Install MaxxMeter on Home Assistant and OTA-flash the office US portrait panel.
#
# Usage:
#   $env:HA_TOKEN = "your-long-lived-access-token"
#   .\scripts\install-office-panel.ps1
#
# Optional:
#   -EsphomeDeviceName "office-panel"   # must match existing ESPHome device name
#   -HaHost "192.168.1.7"

param(
  [string]$HaHost = "192.168.1.7",
  [string]$HaToken = $env:HA_TOKEN,
  [string]$EsPhomeDeviceName = "",
  [string]$RepoUrl = "https://github.com/dougrathbone/maxx-meter"
)

$ErrorActionPreference = "Stop"
$Root = Resolve-Path (Join-Path $PSScriptRoot "..")
$HaBase = "http://${HaHost}:8123"
$Headers = @{ Authorization = "Bearer $HaToken"; "Content-Type" = "application/json" }

function Ha-Post($Path, $Body = "{}") {
  Invoke-RestMethod -Uri "$HaBase$Path" -Method Post -Headers $Headers -Body $Body
}

function Ha-Get($Path) {
  Invoke-RestMethod -Uri "$HaBase$Path" -Method Get -Headers $Headers
}

if (-not $HaToken) {
  Write-Host "Set HA_TOKEN first:"
  Write-Host '  $env:HA_TOKEN = "eyJ..."'
  Write-Host "Create at: $HaBase/profile/security (Long-Lived Access Tokens)"
  exit 1
}

Write-Host "=== 1. Verify Home Assistant ==="
$config = Ha-Get "/api/config"
Write-Host "Connected to: $($config.location_name) ($($config.version))"

Write-Host "`n=== 2. Find ESPHome / NSPanel device ==="
$states = Ha-Get "/api/states"
$matches = $states | Where-Object {
  $_.entity_id -match "esphome|nspanel|office" -or $_.attributes.friendly_name -match "office|nspanel"
}
if ($matches) {
  $matches | Select-Object -First 10 entity_id, @{n="name";e={$_.attributes.friendly_name}} | Format-Table -AutoSize
} else {
  Write-Host "No obvious matches — check ESPHome dashboard for device name."
}

if (-not $EsPhomeDeviceName) {
  Write-Host "Re-run with -EsPhomeDeviceName `"your-esphome-device-name`" (the YAML name: field, not friendly name)"
  Write-Host "Example: .\scripts\install-office-panel.ps1 -EsPhomeDeviceName office-panel"
}

Write-Host "`n=== 3. Add MaxxMeter add-on repository ==="
try {
  Ha-Post "/api/hassio/store/repositories" (@{ repository = $RepoUrl } | ConvertTo-Json)
  Write-Host "Repository added."
} catch {
  Write-Host "Repository may already exist: $($_.Exception.Message)"
}

Write-Host "Refreshing add-on store..."
Ha-Post "/api/hassio/store/repositories/$([uri]::EscapeDataString($RepoUrl))/reload"

Write-Host "`n=== 4. Install MaxxMeter add-on ==="
$addonSlug = "maxxmeter"
try {
  Ha-Post "/api/hassio/addons/$addonSlug/install"
  Write-Host "Install started (may take several minutes to build)..."
} catch {
  Write-Host "Install response: $($_.Exception.Message)"
}

Write-Host "Waiting for add-on to be available..."
Start-Sleep -Seconds 30

Write-Host "`n=== 5. Configure and start MaxxMeter ==="
$options = @{
  poll_interval_seconds = 300
  warn_pct = 70
  critical_pct = 90
  mqtt_host = "core-mosquitto"
  mqtt_port = 1883
  mqtt_username = ""
  mqtt_password = ""
  mqtt_topic_prefix = "maxxmeter"
  ha_url = "http://supervisor/core"
  ha_token = $HaToken
  bootstrap_office_panel = $true
} | ConvertTo-Json

Ha-Post "/api/hassio/addons/$addonSlug/options" $options
Ha-Post "/api/hassio/addons/$addonSlug/start"
Write-Host "MaxxMeter started with bootstrap_office_panel=true"

Write-Host "`n=== 6. Read bootstrap panel credentials from add-on logs ==="
Start-Sleep -Seconds 8
$logs = Invoke-RestMethod -Uri "$HaBase/api/hassio/addons/$addonSlug/logs" -Headers @{ Authorization = "Bearer $HaToken" }
$panelId = [regex]::Match($logs, "panel_id=(\S+)").Groups[1].Value
$apiKey = [regex]::Match($logs, "panel_api_key=(\S+)").Groups[1].Value

if ($panelId -and $apiKey) {
  Write-Host "Panel ID:  $panelId"
  Write-Host "API key:   $apiKey"
  $secretsPath = Join-Path $Root "panel\esphome\secrets.yaml"
  $portraitTftUrl = "https://raw.githubusercontent.com/edwardtfn/NSPanel-Easy/main/hmi/nspanel_portrait.tft"
  @"
# Generated by install-office-panel.ps1 — fill wifi + esphome keys from your existing device
wifi_ssid: "YOUR_WIFI"
wifi_password: "YOUR_WIFI_PASSWORD"
collector_host: "$HaHost"
panel_id: "$panelId"
panel_api_key: "$apiKey"
panel_api_key_bearer: "Bearer $apiKey"
nextion_update_url_us: "$portraitTftUrl"
api_encryption_key: "PASTE_FROM_EXISTING_ESPHOME_CONFIG"
ota_password: "PASTE_FROM_EXISTING_ESPHOME_CONFIG"
"@ | Set-Content -Path $secretsPath -Encoding UTF8
  Write-Host "Wrote $secretsPath — edit wifi + api_encryption_key + ota_password from your ESPHome config"
} else {
  Write-Host "Could not parse panel credentials from logs yet. Check:"
  Write-Host "  $HaBase/hassio/addon/maxxmeter/logs"
  Write-Host "Or register manually in MaxxMeter ingress -> Panels"
}

Write-Host "`n=== 7. OTA flash ESPHome (after secrets.yaml is complete) ==="
if ($EsPhomeDeviceName) {
  $yaml = Join-Path $Root "panel\esphome\office-panel.yaml"
  (Get-Content $yaml -Raw) -replace 'name: office-panel', "name: $EsPhomeDeviceName" | Set-Content $yaml
  Write-Host "Flashing $EsPhomeDeviceName OTA..."
  Push-Location (Join-Path $Root "panel\esphome")
  esphome run office-panel.yaml
  Pop-Location
} else {
  Write-Host "After editing secrets.yaml:"
  Write-Host "  cd panel\esphome"
  Write-Host "  esphome run office-panel.yaml"
}

Write-Host "`nDone. Open MaxxMeter from HA sidebar to connect AI accounts."
